:toc:

= COO - TD4

== Quelques éditeurs UML

* PlantUML
** https://plantuml-editor.kkeisuke.com/
** https://liveuml.com/
** https://www.planttext.com/
** https://plantuml.com/fr/

* StarUML : https://staruml.io/

* Draw.io : https://app.diagrams.net/

== GitHub

GitHub est une plateforme collaborative, basée sur Git.

Git permet de stocker un ensemble de fichiers, tout en conservant la chronologie des modifications.

GitHub met à disposition (entre autres) l'ensemble des actions possibles sur cet ensemble de fichier, depuis le site internet https://github.com/ .

=== A faire (si ce n'est pas déjà fait)

* Créer un compte GitHub (ou se connecter avec un compte existant)
* Créer un repository en cliquant sur l'invitation suivante : https://classroom.github.com/a/WFp1X7Zf
* A la racine du repository, modifier le fichier "*README.md*" :
** mettre vos noms et prénoms
** cocher le groupe de TP "*4*"

Ce repository vous servira pour stocker votre travail de COO. Vous pouvez l'organiser comme vous le souhaitez (ex. un dossier par TD).

Seule obligation, une nomenclature pour les commentaires des commits : `Fix <numéro de l'exercice> : <description de la modification>`

Ex. `Fix 2.1.2 : ajout des acteurs pour le diagramme des UC`

[NOTE]
====
Commit d'un fichier = sauvegarde + le traçage du différentiel entre la version précédente et la version actuelle, pour pouvoir consulter les détails de la modification effectuée
====

== 2. Exercices

=== 2.1 Etablissement scolaire

[plantuml, "td421", png]  
----
@startuml

top to bottom direction

actor :Enseignant responsable:
actor Enseignant
actor Utilisateur

Enseignant --|> Utilisateur
:Enseignant responsable: --|> Enseignant

usecase "Effectuer réservation" as UC1
usecase "Vérifier la disponibilité" as UC1_0
usecase "Réserver salle" as UC1_1
usecase "Réserver matériel" as UC1_2
usecase "Réserver ordinateur" as UC1_2_1
usecase "Réserver vidéo-projecteur" as UC1_2_2
usecase "Consulter planning" as UC2
usecase "Consulter récapitulatif horaire" as UC3
usecase "Editer récapitulatif horaire" as UC4

UC1 --> UC1_0 : <<include>>
UC1_1 --|> UC1
UC1_2 --|> UC1
UC1_2_1 --|> UC1_2
UC1_2_2 --|> UC1_2

Enseignant -- UC1
Utilisateur -- UC2
Enseignant -- UC3
:Enseignant responsable: -- UC4

@enduml
----

=== 2.2 Magasin

[plantuml, "td422", png]  
----
@startuml

top to bottom direction

actor Client
actor Vendeur
actor Caisse
actor Banque

usecase "Prospecter" as UC1
usecase "Essayer" as UC2
usecase "Acheter" as UC3
usecase "Renseigner" as UC4
usecase "Vérifier stock" as UC5
usecase "Bénéficier réduction" as UC6
usecase "Payer" as UC7
usecase "Payer par CB" as UC8
usecase "Payer en liquide" as UC9
usecase "Payer par chèque" as UC10

UC2 --> UC1 : <<extends>>
UC4 --> UC1 : <<extends>>
UC1 --> UC3 : <<extends>>
UC6 --> UC3 : <<extends>>
UC3 --> UC5 : <<include>>
UC3 --> UC7 : <<include>>
UC8 --|> UC7
UC9 --|> UC7
UC10 --|> UC7

Client -- UC1
Client -- UC3
Vendeur -- UC4
Vendeur -- UC5
Caisse -- UC7
Banque -- UC8

@enduml
----